trigger:
 tags:
   include:
     - v*

stages:
- stage: Build
  displayName: Build Test and push stage
  jobs:
  - job: Build
    displayName: Build Test and push stage
    pool:
      vmImage: $(VMIMAGENAME)

    steps:

    - task: SonarQubePrepare@7
      inputs:
        SonarQube: 'Sonar-xown'
        scannerMode: 'dotnet'
        dotnetScannerVersion: '9.2.1.110358'
        projectKey: 'Xownsolutions_Xownsolutions_6a5aca6a-964e-49a9-b422-b08be69dc92e'
        projectName: 'Xownsolutions-Test'
        extraProperties: sonar.branch.name=

    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
      displayName: 'Restore the Project'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        arguments: '--configuration $(BUILDCONFIGURATION)'
        projects: '**/*.csproj'
      displayName: 'Build the Project'
    
  
    - task: SonarQubeAnalyze@7
      inputs:
        jdkversion: 'JAVA_HOME_17_X64'
      env:
        SONAR_SCANNER_OPTS: "-Dsonar.branch.name="
      
    - task: SonarQubePublish@7
      inputs:
        pollingTimeoutSec: '300'
  
    - task: Docker@2
      displayName: Build and push an image to container registry
      condition: succeeded() #Only run if tests pass
      inputs:
        containerRegistry: '247-ACR'
        repository: '247travels-BS-API'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(TAG)'
      
    