trigger:
 tags:
   include:
     - v*

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(VMIMAGENAME)

    steps:

    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
      displayName: 'Restore the Project'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        arguments: '--configuration $(BUILDCONFIGURATION)'
        projects: '**/*.csproj'
      displayName: 'Build the Project'


    - task: Docker@2
      displayName: Build and push an image to container registry
      condition: succeeded() #Only run if tests pass
      inputs:
        containerRegistry: '247-ACR'
        repository: '247travels-BS-API'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(TAG)'
      
    