trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: DotNetCoreCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1(b4d33260-aeee-4fdf-a3b0-6b3b841c473b)'
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
  displayName: 'Restore the Project'

- task: DotNetCoreCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1(b4d33260-aeee-4fdf-a3b0-6b3b841c473b)'
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
    projects: '**/*.csproj'
  displayName: 'Build the Project'
   

- task: DotNetCoreCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1(b4d33260-aeee-4fdf-a3b0-6b3b841c473b)'
    command: 'test'
    projects: '**/*.csproj'
